### ISSUE TITLE
"One bills" instead of "one bill" used to describe sponsorship counts

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates.org#18]
See screenshot for example: "… is the primary sponsor of **_one_ bills**"

![screen shot 2015-01-05 at 16 10 54](https://cloud.githubusercontent.com/assets/4959135/5620037/cd5fafbc-94f5-11e4-8179-403166d7b0f2.png)

**Comment by Divy123** [comment]
Want to work on this issue.

**Comment by jamesturk** [comment]
will be fixed in new site
