### ISSUE TITLE
Shade district instead of using a pin (for legislator pages)

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates.org#19]
For active legislators' pages, we should try to shade their districts' area on the map, instead of putting a point in the middle of it. This is both more accurate and easily understandable. In addition, for odd-shaped districts sometimes the pin will fall outside of the district, or even in another state; [for example, the Illinois 36th Senate seat](http://openstates.org/il/legislators/ILL000022/mike-jacobs/).

**Comment by jamesturk** [comment]
Yeah using the centroid isn't desirable, but the maps are statically
rendered and replacing that would be a pretty significant change.

I think an easier solution might be to use a geolocated point that we know
is within the district or apply some sort of point-in-polygon algorithm.

On Tue, Jan 20, 2015 at 4:55 PM, Miles Watkins <notifications@github.com>
wrote:

> For active legislators' pages, we should try to shade their districts'
> area on the map, instead of putting a point in the middle of it. This is
> both more accurate and easily understandable. In addition, for odd-shaped
> districts sometimes the pin will fall outside of the district, or even in
> another state; for example, the Illinois 36th Senate seat
> <http://openstates.org/il/legislators/ILL000022/mike-jacobs/>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunlightlabs/openstates.org/issues/19>.
>



-- 

James Turk
Labs Director | Sunlight Foundation <http://www.sunlightfoundation.com/>
202-558-8723 | @JamesTurk <https://twitter.com/jamesturk>

[image: Sunlight Foundation] <http://sunlightfoundation.com/>

**Comment by jalbertbowden** [comment]
has this been done? 
![screen shot 2017-09-08 at 8 39 37 pm](https://user-images.githubusercontent.com/46432/30235335-e4a9c576-94d5-11e7-8819-5593a698803c.png)

**Comment by mileswwatkins** [comment]
Ah, this old house!
