### ISSUE TITLE
Switch vote visualizations from pie to bar charts

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates.org#27]
It might be nice to use bar (/column) charts instead of pie charts to display roll call votes.
- In almost all cases, "other" votes don't matter to the passage of a roll call. Therefore, they're confounding to include in a pie chart because they obfuscate the "50%" line that one side or the other needs to pass (but would be fine to include in a bar chart, where comparing "yes" and "no" could be done agnostically to the "other" bar).
- Bar charts fill the rectangular `<div>`s we have better than pie charts, and also scale better in size.
- Bar charts would allow us to indicate absolute values on the scale if we so decided, whereas pie charts only allow visualization of relative values (ie, shares of total).
- For pie slices that don't start at exactly the 12-o'clock mark, it's sometimes difficult to quickly intuit the size of the slice, either in absolute or relative terms. And since the arrangement of the three types of votes ("yes"/"no"/"other") changes from chart to chart, this issue is only made more confounding.

**Comment by mileswwatkins** [comment]
Ah, yes, @jalbertbowden, I've just dropped the ball on reviewing @richardbao97's PR :)

**Comment by jalbertbowden** [comment]
na you're busy...just poking around to see where/if i can contribute something
