### ISSUE TITLE
Local development server refuses connections

### ISSUE THREAD

**Issue by narayanaditya95** [openstates/openstates.org#46]
Hi,

I tried running the development server locally using the command `python manage.py runserver`.
Although the server is active at `localhost:8000`, it refuses every connection with the error code:

```
ConnectionFailure at /
[Errno 61] Connection refused
Exception Location:	/Users/aditya/.virtualenvs/openstates.org/src/billy/billy/core/__init__.py in __getattr__, line 75
```

Am I missing something?

**Comment by jamesturk** [comment]
Hi,

Are you running MongoDB?

**Comment by narayanaditya95** [comment]
Thank you.
That fixed it.
