### ISSUE TITLE
Invoke the openstates virtualenv

### ISSUE THREAD

**Issue by todrobbins** [openstates/openstates.org#49]
As a relative newbie to Python, can someone explain what this statement from [HACKING.md](../blob/master/HACKING.md) mean?

> Invoke the openstates `virtualenv` (most importantly Django 1.8 and Python 2)

**Comment by jamesturk** [comment]
It means that you need to create & activate a virtualenv http://docs.python-guide.org/en/latest/dev/virtualenvs/ that is using Python 2, there's a requirements.txt file to help you install the dependencies to run OS.org
