### ISSUE TITLE
Question on transperancydata_id and missing votesmart_id

### ISSUE THREAD

**Issue by marfi** [openstates/openstates.org#50]
Hi,

I've been looking at: https://openstates.org/csv_downloads/

I think votesmart_id referes to: http://votesmart.org/, however in the file I downloaded: wv_legislators.csv, I do not see such a column.

Also, can you point me to the transparencydata_id source?

**Comment by jamesturk** [comment]
Those IDs are deprecated now, sorry for the trouble.  Transparency Data was a Sunlight site that no longer exists.
